name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v5

    - name: Use FiveM Node.js version
      uses: actions/setup-node@v6
      with:
        node-version: 16.9.1

    - name: Build
      run: |
        yarn install
        yarn build

    - name: Archive Release
      uses: thedoctor0/zip-release@0.7.6
      with:
        type: zip
        filename: resource.zip
        exclusions: '*.git* /*node_modules/* .editorconfig /*server/* /*client/* *.lock .* package.json build.js'

    - name: Automatic release
      uses: softprops/action-gh-release@v2
      with:
        make_latest: true
        tag_name: latest
        prerelease: false
        files: resource.zip
